#ifndef EYE_TRAINER_CONSTANTS
#define EYE_TRAINER_CONSTANTS 0

#define PIN_LED_GND_BUS 6 
#define MAX_LED_INDEX 15
#define MAX_BRIGHTNESS 255.0
#define MIN_BRIGHTNESS 25.5

#define PIN_BTN_MAIN 9
#define PIN_BTN_UP 10
#define PIN_BTN_DOWN 11

#define PIN_DISPLAY_CLK 7
#define PIN_DISPLAY_DIO 8

#define PIN_LED_DATA 5
#define PIN_LED_LATCH 4
#define PIN_LED_CLOCK 3

#define REGISTER_SIZE 2

#define LONG_CLICK_TIME_MS 500

#endif